Models/Carrer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrer()
        {
            this.Applications = new HashSet<Application>();
            this.Requirments = new HashSet<Requirment>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Salary { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirment> Requirments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}

Models/Requirment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Carrer_ID { get; set; }
    
        public virtual Carrer Carrer { get; set; }
    }
}

Models/Skill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Carrer_ID { get; set; }
    
        public virtual Carrer Carrer { get; set; }
    }
}

Controllers/CarrersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RooyaDev.Models;

namespace RooyaDev.Controllers
{
    [Authorize]
    [HandleError(View = "~/Views/Shared/Error.cshtml")]
    public class CarrersController : Controller
    {
        private DB db = new DB();

        // GET: Carrers
        public ActionResult Index()
        {
            if(Session["Skills"]!=null)
            {
                Session.Remove("Skills");
            }
            if (Session["Requirment"] != null)
            {
                Session.Remove("Requirment");
            }
            return View(db.Carrers.ToList());
        }

        // GET: Carrers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Carrer carrer = db.Carrers.Find(id);
            if (carrer == null)
            {
                return HttpNotFound();
            }
            return View(carrer);
        }

        // GET: Carrers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carrers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,Salary,Type,Country")] Carrer carrer)
        {

                if(Session["Skills"]!=null)
                {
                    List<Skill> List = Session["Skills"] as List<Skill>;
                    foreach (var item in List)
                    {
                        carrer.Skills.Add(item);
                    }
                    Session.Remove("Skills");
                }
                if (Session["Requirment"] != null)
                {
                    List<Requirment> List = Session["Requirment"] as List<Requirment>;
                    foreach (var item in List)
                    {
                        carrer.Requirments.Add(item);
                    }
                    Session.Remove("Requirment");
                }
                db.Carrers.Add(carrer);
                db.SaveChanges();
                return RedirectToAction("Index");
        }

        // GET: Carrers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Carrer carrer = db.Carrers.Find(id);
            if (carrer == null)
            {
                return HttpNotFound();
            }
            if (Session["Skills"] != null)
            {
                Session.Remove("Skills");
            }
            if (Session["Requirment"] != null)
            {
                Session.Remove("Requirment");
            }
            return View(carrer);
        }

        // POST: Carrers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Salary,Type,Country")] Carrer carrer)
        {
            if (ModelState.IsValid)
            {
                if (Session["Skills"] != null)
                {
                    List<Skill> List = Session["Skills"] as List<Skill>;
                    foreach (var item in List)
                    {
                        item.Carrer_ID=carrer.ID;
                        db.Skills.Add(item);
                    }
                }
                if (Session["Requirment"] != null)
                {
                    List<Requirment> List = Session["Requirment"] as List<Requirment>;
                    foreach (var item in List)
                    {
                        item.Carrer_ID = carrer.ID;
                        db.Requirments.Add(item);
                    }
                }
                db.Entry(carrer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carrer);
        }
        // POST: Carrers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Carrer carrer = db.Carrers.Find(id);
            db.Carrers.Remove(carrer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddSkill(string Skill)
        {
            if(Session["Skills"]!=null)
            {
                List<Skill> List = Session["Skills"] as List<Skill>;
                List.Add(new Skill { Name = Skill });
                Session["Skills"] = List;
            }
            else
            {
                List<Skill> List = new List<Models.Skill>();
                List.Add(new Skill { Name = Skill });
                Session["Skills"] = List;
            }
            return PartialView("_Skills");
        }

        [HttpPost]
        public ActionResult AddRequirment(string Requirment)
        {
            if (Session["Requirment"] != null)
            {
                List<Requirment> List = Session["Requirment"] as List<Requirment>;
                List.Add(new Requirment { Name = Requirment });
                Session["Requirment"] = List;
            }
            else
            {
                List<Requirment> List = new List<Models.Requirment>();
                List.Add(new Requirment { Name = Requirment });
                Session["Requirment"] = List;
            }
            return PartialView("_Requirment");
        }
        [HttpPost]
        public ActionResult DeleteSkill(int id)
        {
            Skill skill = db.Skills.Find(id);
            Carrer carrer = db.Carrers.Find(skill.Carrer_ID);
            db.Skills.Remove(skill);
            db.SaveChanges();
            return PartialView("_DeleteSkills", carrer);
        }
        [HttpPost]
        public ActionResult DeleteRequirment(int id)
        {
            Requirment requirment = db.Requirments.Find(id);
            Carrer carrer = db.Carrers.Find(requirment.Carrer_ID);
            db.Requirments.Remove(requirment);
            db.SaveChanges();
            return PartialView("_DeleteRequirment", carrer);
        }
        [HttpPost]
        public ActionResult DownloadCV(int id,string name)
        {
            return File(Server.MapPath("~/Uploads/CV/" + id + ".pdf"),"application/pdf",name+".pdf");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Carrers/Details.cshtml
@model RooyaDev.Models.Carrer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-laptop"> </i> <label> Details carrers</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-laptop"></i>Carrer Details</h3> <hr />
        <table class="table table-bordered table-hover white">

            <tr class="alert">
                <td class="col-md-6">Name</td>
                <td class="col-md-6">@Model.Name</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Salary</td>
                <td class="col-md-6">@Model.Salary</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Skills</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Skills)
                        {
                            <li>@item.Name</li>
                        }
                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Requirment</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Requirments)
                        {
                            <li>@item.Name</li>
                        }
                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Type</td>
                <td class="col-md-6">@Model.Type</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Country</td>
                <td class="col-md-6">@Model.Country</td>

            </tr>
            <tr class="alert">
                <td class="col-md-6">Description</td>
                <td class="col-md-6">@Model.Description</td>
            </tr>
        </table>
        <a href="~/Carrers/Edit/@Model.ID;" class="btn btn-info">edit</a>

    </div>
    <h2>Applications</h2>
    <div id="DI">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Name</td>
                <td>Email</td>
                <td>Phone</td>
                <td></td>
            </tr>
            @foreach (var item in Model.Applications)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Email</td>
                    <td>@item.Phone</td>
                    <td>
                        @using (Html.BeginForm("DownloadCV","Carrers",new { id=item.ID,name=item.Name},FormMethod.Post,null))
                        {
                            <button type="submit" class="btn btn-default">Download</button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>

</div>

Views/Carrers/Edit.cshtml
@model RooyaDev.Models.Carrer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-pencil"> </i> <label> Edit Carrer</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-pencil"></i> Edit Carrer</h3> <hr />

        @using (Ajax.BeginForm("AddSkill", "Carrers", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
            {
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Skill</span>
                <input type="text" name="Skill" required class="form-control co-md-7">

                <button type="submit" class="btn btn-success">add</button>
            </div> <br />
        }

        <div id="DIV">
            <table class="table table-info table-hover table-bordered">
                <tr>
                    <td>Skill</td>
                    <td></td>
                </tr>
                @using RooyaDev.Models
                @if (Session["Skills"] != null)
                {
                    foreach (var item in Session["Skills"] as List<Skill>)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>


        @using (Ajax.BeginForm("AddRequirment", "Carrers", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
            {
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Requirment</span>
                <input type="text" name="Requirment" required class="form-control co-md-7">

                <button type="submit" class="btn btn-success">add</button>
            </div> <br />
        }

        <div id="DIV1">
            <table class="table table-info table-hover table-bordered">
                <tr>
                    <td>Requirment</td>
                    <td></td>
                </tr>
                @using RooyaDev.Models
                @if (Session["Requirment"] != null)
                {
                    foreach (var item in Session["Requirment"] as List<Requirment>)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>





        <form action="~/Carrers/Edit" method="post">
            @Html.AntiForgeryToken()
            @Html.Hidden("ID",Model.ID)
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Name</span>
                <input type="text" name="Name" value="@Model.Name" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Salary</span>
                <input type="text" name="Salary" value="@Model.Salary" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Type</span>
                <input type="text" name="Type" value="@Model.Type" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Country</span>
                <input type="text" name="Country" value="@Model.Country" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />

            <div class="input-group textarea">
                <span class="input-group col-md-4" id="basic-addon3"> Description</span>
                <textarea class="form-control col-md-8" name="Description" required id="basic-url" aria-describedby="basic-addon3">@Model.Description </textarea>
            </div> <br />
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
    <h2>Skills</h2>
    <div id="DIV3">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Skill</td>
                <td>Delete</td>
            </tr>
            @foreach (var item in Model.Skills)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>
                        @using (Ajax.BeginForm("DeleteSkill", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV3", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
    <br/><br/>
    <h2>Requirment</h2>
    <div id="DIV4">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Requirment</td>
                <td>Delete</td>
            </tr>
            @foreach (var item in Model.Requirments)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>
                        @using (Ajax.BeginForm("DeleteRequirment", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV4", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Views/Carrers/Index.cshtml
@model IEnumerable<RooyaDev.Models.Carrer>

@{
    ViewBag.Title = "Carrers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-tags"> </i> <label> Carrers</label>
                </div>

            </div>
        </div>

    </header><!-- /header -->
    <!-- Header-->


    <div class="col-md-12">
        <button data-toggle="modal" data-target="#modal1" class="btn btn-success"><i class="fa fa-plus-square"></i> &nbsp; ADD</button>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"></div>
            <div class="panel-body">
                <p></p>
            </div>

            <!-- Table -->
            <table class="table table-hover table-bordered">
                <tr>
                    <td>Name</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-md-4">@item.Name</td>
                        <td class="col-md-2">
                            <a href="~/Carrers/Edit/@item.ID" class="btn btn-info">Edit</a>
                        </td>
                        <td class="col-md-2">
                            <a href="~/Carrers/Details/@item.ID" class="btn btn-primary">
                                Details
                            </a>
                        </td>
                        <td class="col-md-2">
                        
                            @using (Html.BeginForm("Delete", "Carrers", new { id = item.ID }, FormMethod.Post, null))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" onclick="return confirm('Are You Sure You Want Delete This Carrer ?!');" class="btn btn-danger">Delete</button>
                            }   
                        
                        </td>
                    </tr>

                }

            </table>

        </div>
        <hr />
    </div><!-- .content -->

</div> <!-- /#right-panel -->
<!-- Right Panel -->

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <h3 class="white"><i class="fa fa-plus-square"></i> Add Carrers</h3> <hr />
            @using (Ajax.BeginForm("AddSkill", "Carrers", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
            {
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Skill</span>
                    <input type="text" name="Skill" required class="form-control co-md-7">

                    <button type="submit" class="btn btn-success">add</button>
                </div> <br />
            }

            <div id="DIV">
                <table class="table table-info table-hover table-bordered">
                    <tr>
                        <td>Skill</td>
                        <td></td>
                    </tr>
                    @using RooyaDev.Models
                    @if (Session["Skills"] != null)
                    {
                        foreach (var item in Session["Skills"] as List<Skill>)
                        {
                            <tr>
                                <td>
                                    @item.Name
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>


            @using (Ajax.BeginForm("AddRequirment", "Carrers", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
            {
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Requirment</span>
                    <input type="text" name="Requirment" required class="form-control co-md-7">

                    <button type="submit" class="btn btn-success">add</button>
                </div> <br />
            }

            <div id="DIV1">
                <table class="table table-info table-hover table-bordered">
                    <tr>
                        <td>Requirment</td>
                        <td></td>
                    </tr>
                    @using RooyaDev.Models
                    @if (Session["Requirment"] != null)
                    {
                        foreach (var item in Session["Requirment"] as List<Requirment>)
                        {
                            <tr>
                                <td>
                                    @item.Name
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>




                
            <form action="~/Carrers/Create" method="post">
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Name</span>
                    <input type="text" name="Name" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Salary</span>
                    <input type="text" name="Salary" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Type</span>
                    <input type="text" name="Type" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Country</span>
                    <input type="text" name="Country" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />

                <div class="input-group textarea">
                    <span class="input-group col-md-4" id="basic-addon3"> Description</span>
                    <textarea class="form-control col-md-8" name="Description" required id="basic-url" aria-describedby="basic-addon3"> </textarea>
                </div> <br />

                <button type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>
</div>

Views/Carrers/_DeleteRequirment.cshtml
@model RooyaDev.Models.Carrer
<div id="DIV4">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Requirment</td>
            <td>Delete</td>
        </tr>
        @foreach (var item in Model.Requirments)
            {
            <tr>
                <td>@item.Name</td>
                <td>
                    @using (Ajax.BeginForm("DeleteRequirment", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV4", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Carrers/_DeleteSkills.cshtml
@model RooyaDev.Models.Carrer
    <div id="DIV3">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Skill</td>
            <td>Delete</td>
        </tr>
        @foreach (var item in Model.Skills)
            {
            <tr>
                <td>@item.Name</td>
                <td>
                    @using (Ajax.BeginForm("DeleteSkill", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV3", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Carrers/_Requirment.cshtml
<div id="DIV1">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Requirment</td>
            <td></td>
        </tr>
        @using RooyaDev.Models
        @if (Session["Requirment"] != null)
        {
            foreach (var item in Session["Requirment"] as List<Requirment>)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                </tr>
            }
        }
    </table>
</div>

Views/Carrers/_Skills.cshtml
<div id="DIV">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Skill</td>
            <td></td>
        </tr>
        @using RooyaDev.Models
        @if (Session["Skills"] != null)
        {
            foreach (var item in Session["Skills"] as List<Skill>)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                </tr>
            }
        }
    </table>
</div>