Models/Gallery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Name_AR { get; set; }
        public string Description_AR { get; set; }
    }
}

Controllers/GalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RooyaDev.Models;
using System.IO;

namespace RooyaDev.Controllers
{
    [Authorize]
    [HandleError(View = "~/Views/Shared/Error.cshtml")]
    public class GalleriesController : Controller
    {
        private DB db = new DB();

        // GET: Galleries
        public ActionResult Index()
        {
            return View(db.Galleries.ToList());
        }

        // GET: Galleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Name_AR,Description,Description_AR")] Gallery gallery,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid&&Photo!=null)
            {
                db.Galleries.Add(gallery);
                db.SaveChanges();
                Photo.SaveAs(Server.MapPath("~/Uploads/Gallery/" + gallery.ID + ".jpg"));
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Galleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Name_AR,Description,Description_AR")] Gallery gallery,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gallery).State = EntityState.Modified;
                db.SaveChanges();
                if(Photo!=null)
                {
                    Photo.SaveAs(Server.MapPath("~/Uploads/Gallery/" + gallery.ID + ".jpg"));
                }
                return RedirectToAction("Index");
            }
            return View(gallery);
        }


        // POST: Galleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            db.Galleries.Remove(gallery);
            db.SaveChanges();
            FileInfo F = new FileInfo(Server.MapPath("~/Uploads/Gallery/" + id + ".jpg"));
            if(F.Exists)
            {
                F.Delete();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Galleries/Details.cshtml
@model RooyaDev.Models.Gallery

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-laptop"> </i> <label> Protofolio Details</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-laptop"></i> Protofolio Details</h3> <hr />
        <table class="table table-bordered table-hover white">

            <tr class="alert">
                <td class="col-md-2">Name</td>
                <td class="col-md-10">@Model.Name</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Name AR</td>
                <td class="col-md-10">@Model.Name_AR</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Description</td>
                <td class="col-md-10">@Model.Description</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Description AR</td>
                <td class="col-md-10">@Model.Description_AR</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Photo</td>
                <td class="col-md-10"><img src="~/Uploads/Gallery/@(Model.ID).jpg"  width="100" height="100" style="border-radius:50%" /></td>
            </tr>
        </table>
        <a href="~/Galleries/Edit/@Model.ID" class="btn btn-info">edit</a>

    </div>
</div>

Views/Galleries/Edit.cshtml
@model RooyaDev.Models.Gallery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-pencil"> </i> <label> Edit Protfolio</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-pencil"></i> Edit Protfolio</h3> <hr />
        <form action="~/Galleries/Edit" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            @Html.Hidden("ID", Model.ID)
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Name</span>
                <input type="text" class="form-control col-md-8" value="@Model.Name"  name="Name" required id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Name AR</span>
                <input type="text" class="form-control col-md-8" value="@Model.Name_AR" name="Name_AR" required id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Description</span>
                <textarea class="form-control col-md-8" name="Description" required id="basic-url" aria-describedby="basic-addon3">@Model.Description </textarea>
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Description AR</span>
                <textarea class="form-control col-md-8" name="Description_AR" required id="basic-url" aria-describedby="basic-addon3">@Model.Description_AR </textarea>
            </div> <br />

            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Upload Photo</span>
                <input type="file" class="col-md-8" name="Photo" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <button type="submit" class="btn btn-success">save</button>
        </form>
    </div>
</div>

Views/Galleries/Index.cshtml
@model IEnumerable<RooyaDev.Models.Gallery>

@{
    ViewBag.Title = "Protfolio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


 <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-file-o"> </i> <label> Protfolio</label>
                </div>

            </div>
        </div>

    </header><!-- /header -->
    <!-- Header-->


    <div class="col-md-12">
        <button data-toggle="modal" data-target="#modal1" class="btn btn-success"><i class="fa fa-plus-square"></i> &nbsp; ADD</button>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"></div>
            <div class="panel-body">
                <p></p>
            </div>

            <!-- Table -->
            <table class="table table-hover table-bordered">
                <tr>
                    <td>Name</td>
                    <td>Photo</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-md-3">@item.Name</td>
                        <td class="col-md-3"><img src="~/Uploads/Gallery/@(item.ID).jpg" /></td>
                        <td class="col-md-2">
                            <a href="~/Galleries/Edit/@item.ID" class="btn btn-info">Edit</a>
                        </td>
                        <td class="col-md-2">
                            <a href="~/Galleries/Details/@item.ID" class="btn btn-primary">
                                Details
                            </a>
                        </td>
                        <td class="col-md-2">
                            @using (Html.BeginForm("Delete", "Galleries", new { id = item.ID }, FormMethod.Post, null))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" onclick="return confirm('Are You Sure You Want Delete This Image ?!');" class="btn btn-danger">Delete</button>
                            }
                        </td>
                    </tr>

                }

            </table>
        </div>
    </div><!-- .content -->

</div> <!-- /#right-panel -->
<!-- Right Panel -->

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <h3 class="white"><i class="fa fa-plus-square"></i> Add Protfolio</h3> <hr />
            <form action="~/Galleries/Create" method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Name</span>
                    <input type="text" class="form-control col-md-8" name="Name" required id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Name AR</span>
                    <input type="text" class="form-control col-md-8" name="Name_AR" required id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Description</span>
                    <textarea class="form-control col-md-8" name="Description" required id="basic-url" aria-describedby="basic-addon3"> </textarea>
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Description AR</span>
                    <textarea class="form-control col-md-8" name="Description_AR" required id="basic-url" aria-describedby="basic-addon3"> </textarea>
                </div> <br />

               <div class="input-group">
                     <span class="input-group col-md-4" id="basic-addon3">Upload Photo</span>
                    <input type="file" class="col-md-8" id="basic-url" name="Photo" required aria-describedby="basic-addon3">
                </div> <br />
        <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>
    </div>
</div>