Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Tasks = new HashSet<Task>();
            this.Project_Videos = new HashSet<Project_Videos>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool UnderWork { get; set; }
        public bool Finished { get; set; }
        public System.DateTime Expire_Date { get; set; }
        public string Description { get; set; }
        public int User_ID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Videos> Project_Videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Project_ID { get; set; }
        public Nullable<bool> Finished { get; set; }
    
        public virtual Project Project { get; set; }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RooyaDev.Models;
using System.IO;
using System.Globalization;

namespace RooyaDev.Controllers
{
    [Authorize]
    [HandleError(View = "~/Views/Shared/Error.cshtml")]
    public class ProjectsController : Controller
    {
        private DB db = new DB();

        // GET: Projects
        public ActionResult Index()
        {
            if(Session["Tasks"]!=null)
            {
                Session.Remove("Tasks");
            }
            if (Session["Links"] != null)
            {
                Session.Remove("Links");
            }
            var projects = db.Projects.Include(p => p.User);
            return View(projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }
        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,UnderWork,Finished,Expire_Date,Description,User_ID")] Project project,List<HttpPostedFileBase> Photos,HttpPostedFileBase logo,string Expire_Date)
        {
            if (Request.Cookies["Language"] != null)
            {
                if (Request.Cookies["Language"].Value == "ar")
                {
                    project.Expire_Date = Convert.ToDateTime(Expire_Date, new CultureInfo("ar-AE"));
                }
                else
                {
                    project.Expire_Date = Convert.ToDateTime(Expire_Date);
                }
            }
            else
            {
                project.Expire_Date = Convert.ToDateTime(Expire_Date);
            }
            if (Session["Tasks"]!=null)
                {
                    List<Task> List = Session["Tasks"] as List<Task>;
                    foreach (var item in List)
                    {
                        project.Tasks.Add(item);
                    }
                    Session.Remove("Tasks");
                }
                if (Session["Links"] != null)
                {
                    List<Project_Videos> List = Session["Links"] as List<Project_Videos>;
                    foreach (var item in List)
                    {
                        project.Project_Videos.Add(item);
                    }
                    Session.Remove("Links");
                }
                db.Projects.Add(project);
                db.SaveChanges();
                if(Photos[0]!=null)
                {
                    foreach (var item in Photos)
                    {
                        item.SaveAs(Server.MapPath("~/Uploads/Projects/" + project.ID + "Img" + item.FileName));
                    }
                }
                if (logo != null)
                {
                    logo.SaveAs(Server.MapPath("~/Uploads/Project_Logo/" + project.ID + ".jpg"));
                }
                return RedirectToAction("Index");         
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            if (Session["Tasks"] != null)
            {
                Session.Remove("Tasks");
            }
            if (Session["Links"] != null)
            {
                Session.Remove("Links");
            }
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Name", project.User_ID);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,UnderWork,Finished,Expire_Date,Description,User_ID")] Project project,List<HttpPostedFileBase>Photos,HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {
                if (Session["Tasks"] != null)
                {
                    List<Task> List = Session["Tasks"] as List<Task>;
                    foreach (var item in List)
                    {
                        item.Project_ID = project.ID;
                        db.Tasks.Add(item);
                    }
                    Session.Remove("Tasks");
                }
                if (Session["Links"] != null)
                {
                    List<Project_Videos> List = Session["Links"] as List<Project_Videos>;
                    foreach (var item in List)
                    {
                        item.Project_ID = project.ID;
                        db.Project_Videos.Add(item);
                    }
                    Session.Remove("Links");
                }
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                if(Photos[0]!=null)
                {
                    foreach (var item in Photos)
                    {
                        item.SaveAs(Server.MapPath("~/Uploads/Projects/" + project.ID + "Img" + item.FileName));
                    }
                }
                if(logo!=null)
                {
                    logo.SaveAs(Server.MapPath("~/Uploads/Project_Logo/"+project.ID+".jpg"));
                }
                return RedirectToAction("Index");
            }
            ViewBag.User_ID = new SelectList(db.Users, "ID", "Name", project.User_ID);
            return View(project);
        }
        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            string[]files= Directory.GetFiles(Server.MapPath("~/Uploads/Projects"), id + "*");
            foreach (var item in files)
            {
                FileInfo F = new FileInfo(item);
                if(F.Exists)
                {
                    F.Delete();
                }
            }
            FileInfo Logo = new FileInfo(Server.MapPath("~/Uploads/Project_Logo/" + id + ".jpg"));
            if(Logo.Exists)
            {
                Logo.Delete();
            }
            FileInfo File = new FileInfo(Server.MapPath("~/Uploads/Project_File/" + id + ".pdf"));
            if (File.Exists)
            {
                File.Delete();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddTask(string Task)
        {
            if(Session["Tasks"]!=null)
            {
                List<Task> List = Session["Tasks"] as List<Task>;
                List.Add(new Task { Name = Task });
                Session["Tasks"] = List;
            }
            else
            {
                List<Task> List = new List<Task>();
                List.Add(new Task { Name = Task });
                Session["Tasks"] = List;
            }
            return PartialView("_Tasks");
        }
        [HttpPost]
        public ActionResult DeleteTask(int id)
        {
            Task task = db.Tasks.Find(id);
            Project project = db.Projects.Find(task.Project_ID);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return PartialView("_DeleteTask",project);
        }
        [HttpPost]
        public ActionResult DeletePhoto(string Path,int id)
        {
            Project project = db.Projects.Find(id);
            FileInfo F = new FileInfo(Path);
            if(F.Exists)
            {
                F.Delete();
            }
            return PartialView("_DeletePhoto", project);           
        }
        [HttpPost]
        public ActionResult AddLink(string url)
        {
            if(Session["Links"]!=null)
            {
                List<Project_Videos> List = Session["Links"] as List<Project_Videos>;
                List.Add(new Project_Videos { Link = url });
                Session["Links"] = List;
            }
            else
            {
                List<Project_Videos> List = new List<Project_Videos>();
                List.Add(new Project_Videos { Link = url });
                Session["Links"] = List;
            }
            return PartialView("_Links");
        }
        [HttpPost]
        public ActionResult DeleteLink(int id)
        {
            Project_Videos Link = db.Project_Videos.Find(id);
            Project project = db.Projects.Find(Link.Project_ID);
            db.Project_Videos.Remove(Link);
            db.SaveChanges();
            return PartialView("_DeleteLinks", project);
        }
        [HttpPost]
        public ActionResult FinishTask(int id)
        {
            Task task = db.Tasks.Find(id);
            Project project = db.Projects.Find(task.Project_ID);
            task.Finished = true;
            db.Entry(task).State = EntityState.Modified;
            db.SaveChanges();
            return PartialView("_DeleteTask", project);
        }
        [HttpPost]
        public ActionResult Download(string path,string name)
        {
            return File(path, "application/pdf", name + ".pdf");

Views/Projects/Details.cshtml
@model RooyaDev.Models.Project

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.IO
  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-laptop"> </i> <label> Project Details </label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-laptop"></i> Project Details </h3> <hr />
        <table class="table table-bordered table-hover white">
            <tr class="alert">
                <td class="col-md-6">Logo</td>
                <td class="col-md-6"><img src="~/Uploads/Project_Logo/@(Model.ID).jpg" alt="" /></td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Name</td>
                <td class="col-md-6">@Model.Name</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Tasks</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Tasks)
                        {
                            <li>@item.Name

                            @if(item.Finished.HasValue)
                            {
                                if(item.Finished.Value==true)
                                {
                                    <i class="fa fa-check"></i>
                                }
                                else
                                {
                                   <i class="fa fa-align-center"></i> 
                                }
                            }
                            else
                            {
                               <i class="fa fa-align-center"></i> 
                            }
                        </li>
                        }
                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Links</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Project_Videos)
                        {
                            <li>@item.Link</li>
                        }
                    </ol>
                </td>
            </tr>

            <tr class="alert">
                <td class="col-md-6">DeadLine</td>
                <td class="col-md-6">@Model.Expire_Date</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Under Word</td>
                <td class="col-md-6">@Html.DisplayFor(model=>model.UnderWork)</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Finished</td>
                <td class="col-md-6">@Html.DisplayFor(model => model.Finished)</td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Comments</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Comments)
                        {
                            <li>@item.Comment1</li>
                        }
                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-6">Photos</td>
                <td class="col-md-6">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Directory.GetFiles(Server.MapPath("~/Uploads/Projects"), Model.ID + "*"))
                        {
                            string name = Path.GetFileName(item);
                            <li><img src="~/Uploads/Projects/@name" alt="" width="200" height="200" /></li>
                        }
                    </ol>
                </td>
            </tr>
            @{ 
                FileInfo F = new FileInfo(Server.MapPath("~/Uploads/Project_File/" + Model.ID + ".pdf"));
            }
                @if (F.Exists)
                {
                    <tr class="alert">
                        <td class="col-md-6">Project File</td>
                        <td class="col-md-6">
                            @using (Html.BeginForm("Download", "Projects", new { path = Server.MapPath("~/Uploads/Project_File/" + Model.ID + ".pdf"),name = Model.Name }, FormMethod.Post, null))
                            {
                                <input id="Submit1" type="submit" value="Download" class="btn-primary" />
                            }
                        </td>
                    </tr>
                }

        </table>
        <a href="~/Projects/Edit/@Model.ID" class="btn btn-info">edit</a>

    </div>
</div>

Views/Projects/Edit.cshtml
@model RooyaDev.Models.Project
@using System.IO;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

   <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-pencil"> </i> <label> Edit Project</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-pencil"></i> Edit Project</h3> <hr />
       
        @using (Ajax.BeginForm("AddTask", "Projects", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
            {
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Task</span>
                <input type="text" name="Task" required class="form-control co-md-7">

                <button type="submit" class="btn btn-success">add</button>
            </div> <br />
        }

        <div id="DIV">
            <table class="table table-info table-hover table-bordered">
                <tr>
                    <td>Task</td>
                    <td></td>
                </tr>
                @using RooyaDev.Models
                @if (Session["Tasks"] != null)
                {
                    foreach (var item in Session["Tasks"] as List<Task>)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
        @using (Ajax.BeginForm("AddLink", "Projects", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "Links", InsertionMode = InsertionMode.Replace }))
            {
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Embed Url</span>
                <input type="text" name="url" required class="form-control co-md-7">

                <button type="submit" class="btn btn-success">add</button>
            </div> <br />
        }

        <div id="Links">
            <table class="table table-info table-hover table-bordered">
                <tr>
                    <td>Embed Url</td>
                    <td></td>
                </tr>
                @using RooyaDev.Models
                @if (Session["Links"] != null)
                {
                    foreach (var item in Session["Links"] as List<Project_Videos>)
                    {
                        <tr>
                            <td>
                                @item.Link
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>




        
        
        
         <form action="~/Projects/Edit" method="post" enctype="multipart/form-data">
   
             @Html.AntiForgeryToken()
             @Html.Hidden("ID",Model.ID)
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Name</span>
                 <input type="text" value="@Model.Name" class="form-control co-md-7" name="Name" required>
             </div> <br />

             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Description</span>
                 <textarea class="form-control col-md-8" name="Description" required id="basic-url" aria-describedby="basic-addon3"> @Model.Description</textarea>
             </div> <br />
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">DeadLine</span>
                 <input id="Text1" value="@Model.Expire_Date" type="text" name="Expire_Date" required class="form-control co-md-7" />
              </div> <br />
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">User</span>
                 @Html.DropDownList("User_ID", new SelectList(new DB().Users, "ID", "Name",Model.ID.ToString()), new { @class = "form-control dropdown col-md-8", required = "required" })
             </div> <br />
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Under Work</span>
                 @Html.EditorFor(model => model.UnderWork)
             </div> <br />
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Finish</span>
                 @Html.EditorFor(model => model.Finished)
             </div> <br />

             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Upload Logo</span>
                 <input type="file" name="logo" class="col-md-8" id="basic-url" aria-describedby="basic-addon3">
             </div> <br />
             <div class="input-group">
                 <span class="input-group col-md-4" id="basic-addon3">Upload Photos</span>
                 <input type="file" name="Photos" class="col-md-8" id="basic-url" aria-describedby="basic-addon3" multiple>
             </div> <br />
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
    <h2>Tasks</h2>
    <div id="DIV1">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Task</td>
                <td>Delete</td>
                <td>Finish</td>
            </tr>
            @foreach (var item in Model.Tasks.OrderBy(x=>x.ID))
            {
                <tr>
                    <td>@item.Name</td>
                    <td>
                        @using (Ajax.BeginForm("DeleteTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                    <td>
                        @if (item.Finished.HasValue)
                        {
                            if (item.Finished.Value == true)
                            {
                                <i class="fa fa-check"></i>
                            }
                            else
                            {
                                <i class="fa fa-align-center"></i>
                                using (Ajax.BeginForm("FinishTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                                {
                                    <button type="submit"><i class="fa fa-check"></i></button>
                                }
                            }
                        }
                        else
                        {
                            <i class="fa fa-align-center"></i>
                            using (Ajax.BeginForm("FinishTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                            {
                                <button type="submit"><i class="fa fa-check"></i></button>
                            }

                         }
                    </td>
                    <td>

                    </td>
                </tr>
            }

        </table>
    </div>
    <h2>Links</h2>
    <div id="Link">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Url</td>
                <td>Delete</td>
            </tr>
            @foreach (var item in Model.Project_Videos)
            {
                <tr>
                    <td>@item.Link</td>
                    <td>
                        @using (Ajax.BeginForm("DeleteLink", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "Link", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
    <br/>
    <h2>Photos</h2>
    <div id="DIV2">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Photo</td>
                <td>Delete</td>
            </tr>
            @foreach (var item in Directory.GetFiles(Server.MapPath("~/Uploads/Projects"),Model.ID+"*"))
            {
                string name = Path.GetFileName(item);
                <tr>
                    <td><img src="~/Uploads/Projects/@name" width="100" height="100" alt="" /></td>
                    <td>
                        @using (Ajax.BeginForm("DeletePhoto", new { Path = item,id=Model.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV2", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Views/Projects/_DeleteLinks.cshtml
@model RooyaDev.Models.Project

<div id="Link">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Url</td>
            <td>Delete</td>
        </tr>
        @foreach (var item in Model.Project_Videos)
            {
            <tr>
                <td>@item.Link</td>
                <td>
                    @using (Ajax.BeginForm("DeleteLink", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "Links", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Projects/_DeletePhoto.cshtml
@model RooyaDev.Models.Project
    @using System.IO;
<div id="DIV2">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Photo</td>
            <td>Delete</td>
        </tr>
        @foreach (var item in Directory.GetFiles(Server.MapPath("~/Uploads/Projects"), Model.ID + "*"))
        {
            string name = Path.GetFileName(item);
            <tr>
                <td><img src="~/Uploads/Projects/@name" width="100" height="100" alt="" /></td>
                <td>
                    @using (Ajax.BeginForm("DeletePhoto", new { Path = item,id=Model.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV2", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Projects/_DeleteTask.cshtml
@model RooyaDev.Models.Project
<div id="DIV1">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Task</td>
            <td>Delete</td>
            <td>Finish</td>
        </tr>
        @foreach (var item in Model.Tasks.OrderBy(x => x.ID))
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    @using (Ajax.BeginForm("DeleteTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
                <td>
                    @if (item.Finished.HasValue)
                    {
                        if (item.Finished.Value == true)
                        {
                            <i class="fa fa-check"></i>
                        }
                        else
                        {
                            <i class="fa fa-align-center"></i>
                            using (Ajax.BeginForm("FinishTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                            {
                                <button type="submit"><i class="fa fa-check"></i></button>
                            }
                        }
                    }
                    else
                    {
                        <i class="fa fa-align-center"></i>
                        using (Ajax.BeginForm("FinishTask", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-check"></i></button>
                        }

                    }
                </td>
                <td></td>
            </tr>
        }

    </table>
</div>

Views/Projects/_Links.cshtml
<div id="Links">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Embed Url</td>
            <td></td>
        </tr>
        @using RooyaDev.Models
        @if (Session["Links"] != null)
        {
            foreach (var item in Session["Links"] as List<Project_Videos>)
            {
                <tr>
                    <td>
                        @item.Link
                    </td>
                </tr>
            }
        }
    </table>
</div>