Models/Head.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Service_ID { get; set; }
        public string Name_AR { get; set; }
    
        public virtual Service Service { get; set; }
    }
}

Models/Service.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Heads = new HashSet<Head>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Name_AR { get; set; }
        public string Description_AR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Head> Heads { get; set; }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RooyaDev.Models;
using System.IO;

namespace RooyaDev.Controllers
{
    [Authorize]
    [HandleError(View = "~/Views/Shared/Error.cshtml")]
    public class ServicesController : Controller
    {
        private DB db = new DB();

        // GET: Services
        public ActionResult Index()
        {
            if(Session["Heads"]!=null)
            {
                Session.Remove("Heads");
            }
            return View(db.Services.ToList());
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Name_AR,Description,Description_AR")] Service service,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid&&Photo!=null)
            {
                if(Session["Heads"]!=null)
                {
                    List<Head> List = Session["Heads"] as List<Head>;
                    foreach (var item in List)
                    {
                        service.Heads.Add(item);
                    }
                }
                db.Services.Add(service);
                db.SaveChanges();
                Photo.SaveAs(Server.MapPath("~/Uploads/Services/" + service.ID + ".jpg"));
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            if (Session["Heads"] != null)
            {
                Session.Remove("Heads");
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Name_AR,Description,Description_AR")] Service service ,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                if (Session["Heads"] != null)
                {
                    List<Head> List = Session["Heads"] as List<Head>;
                    foreach (var item in List)
                    {
                        item.Service_ID = service.ID;
                        db.Heads.Add(item);
                    }
                }
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                if(Photo!=null)
                {
                    Photo.SaveAs(Server.MapPath("~/Uploads/Services/" + service.ID + ".jpg"));
                }
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            FileInfo F = new FileInfo(Server.MapPath("~/Uploads/Services/" + id + ".jpg"));
            if(F.Exists)
            {
                F.Delete();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddHead(string Head, string Head_AR)
        {
            if(Session["Heads"]!=null)
            {
                List<Head> List = Session["Heads"] as List<Head>;
                List.Add(new Head { Name = Head ,Name_AR=Head_AR});
                Session["Heads"] = List;
            }
            else
            {
                List<Head> List = new List<Models.Head>();
                List.Add(new Head { Name = Head,Name_AR=Head_AR });
                Session["Heads"] = List;
            }
            return PartialView("_Heads");
        }

        [HttpPost]
        public ActionResult DeleteHead(int id)
        {
            Head head = db.Heads.Find(id);
            db.Heads.Remove(head);
            db.SaveChanges();
            Service service = db.Services.Find(head.Service_ID);
            return PartialView("_DeleteHeads",service);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Services/Details.cshtml
@model RooyaDev.Models.Service

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-laptop"> </i> <label> Details Services</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-laptop"></i> Service Details</h3> <hr />
        <table class="table table-bordered table-hover white">
            <tr class="alert">
                <td class="col-md-2">Name</td>
                <td class="col-md-10">@Model.Name</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Name AR</td>
                <td class="col-md-10">@Model.Name_AR</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Head</td>
                <td class="col-md-10" style="width:inherit">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Heads)
                        {
                            <li>@item.Name</li>
                        }                        

                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Head AR</td>
                <td class="col-md-10" style="width:inherit">
                    <ol class="list-group list-group-item list-group-item-info">
                        @foreach (var item in Model.Heads)
                        {
                            <li>@item.Name_AR</li>
                        }

                    </ol>
                </td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Description</td>
                <td class="col-md-10">@Model.Description</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Description AR</td>
                <td class="col-md-10">@Model.Description_AR</td>
            </tr>
            <tr class="alert">
                <td class="col-md-2">Photo</td>
                <td class="col-md-10">
                    <img src="~/Uploads/Services/@(Model.ID).jpg" width="100" height="100" style="border-radius:50%" />
                </td>
            </tr>
        </table>
        <a href="~/Services/Edit/@Model.ID" class="btn btn-info">Edit</a>

    </div>
</div>

Views/Services/Edit.cshtml
@model RooyaDev.Models.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

   <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-pencil"> </i> <label> Edit services</label>
                </div>
                <div class="header-left">
                </div>
            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->
    <div class="col-md-12">
        <h3 class="white"><i class="fa fa-pencil"></i> Edit services</h3> <hr />
        
        @using (Ajax.BeginForm("AddHead", "Services", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
            {
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Head</span>
                <input type="text" name="Head" required class="form-control co-md-8">
        </div>
        <div class="input-group">

            <span class="input-group col-md-4" id="basic-addon3">Head AR</span>
            <input type="text" name="Head_AR" required class="form-control co-md-8">
        </div>
            <button type="submit" class="btn btn-success">add</button>
        <br />
        }

        <div id="DIV">
            <table class="table table-info table-hover table-bordered">
                <tr>
                    <td>Head</td>
                    <td>Head AR</td>
                </tr>
                @using RooyaDev.Models
                @if (Session["Heads"] != null)
                {
                    foreach (var item in Session["Heads"] as List<Head>)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Name_AR
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>

        <form action="~/Services/Edit" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            @Html.Hidden("ID",Model.ID)
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Name</span>
                <input type="text" value="@Model.Name" name="Name" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Name AR</span>
                <input type="text" value="@Model.Name_AR" name="Name_AR" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <div class="input-group textarea">
                <span class="input-group col-md-4" id="basic-addon3"> Description</span>
                <textarea name="Description" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">@Model.Description </textarea>
            </div> <br />
            <div class="input-group textarea">
                <span class="input-group col-md-4" id="basic-addon3"> Description AR</span>
                <textarea name="Description_AR" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">@Model.Description_AR </textarea>
            </div> <br />
            <div class="input-group">
                <span class="input-group col-md-4" id="basic-addon3">Upload Photo</span>
                <input type="file" name="Photo" class="col-md-8" id="basic-url" aria-describedby="basic-addon3">
            </div> <br />
            <button type="submit" class="btn btn-success">save</button>
        </form>
    </div>
    <h2>Heads</h2>
    <div id="DIV1">
        <table class="table table-info table-hover table-bordered">
            <tr>
                <td>Head</td>
                <td>Head AR</td>
                <td>Delete</td>
            </tr>
            @foreach (var item in Model.Heads)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Name_AR</td>
                    <td>
                        @using (Ajax.BeginForm("DeleteHead", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV1", InsertionMode = InsertionMode.Replace }))
                        {
                            <button type="submit"><i class="fa fa-times"></i></button>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Views/Services/Index.cshtml
@model IEnumerable<RooyaDev.Models.Service>

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="header-menu">
            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="center">
                    <i class="fa fa-briefcase"> </i> <label> Services</label>
                </div>

            </div>
        </div>

    </header><!-- /header -->
    <!-- Header-->


    <div class="col-md-12">
        <button data-toggle="modal" data-target="#modal1" class="btn btn-success"><i class="fa fa-plus-square"></i> &nbsp; ADD</button>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"></div>
            <div class="panel-body">
                <p></p>
            </div>

            <!-- Table -->
            <table class="table table-hover table-bordered">
                <tr>
                    <td>Name</td>
                    <td>Photo</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-md-4">@item.Name</td>
                        <td class="col-md-2"><img src="~/Uploads/Services/@(item.ID).jpg" /></td>
                        <td class="col-md-2">
                            <a href="~/Services/Edit/@item.ID" class="btn btn-info">Edit</a>
                        </td>
                        <td class="col-md-2">
                            <a href="~/Services/Details/@item.ID" class="btn btn-primary">
                                Details
                            </a>
                        </td>
                        <td class="col-md-2">
                        @using (Html.BeginForm("Delete", "Services", new { id = item.ID }, FormMethod.Post, null))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" onclick="return confirm('Are You Sure You Want Delete This Service ?!');" class="btn btn-danger">Delete</button>
                        }                        
                        </td>
                    </tr>

                }
            </table>

        </div>
       
    </div><!-- .content -->

</div> <!-- /#right-panel -->
<!-- Right Panel -->

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <h3 class="white"><i class="fa fa-plus-square"></i> Add Service</h3> <hr />
            @using (Ajax.BeginForm("AddHead", "Services", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
            {
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Head</span>
                    <input type="text" name="Head" style="width:unset" required class="form-control co-md-7">
            <br />
                    <span class="input-group col-md-4" id="basic-addon3">Head AR</span>
                    <input type="text" name="Head_AR" style="width:unset" required class="form-control co-md-7">
            <br />
                    <button type="submit" class="btn btn-success">add</button>
                </div> <br />
            }

                <div id="DIV">
                    <table class="table table-info table-hover table-bordered">
                        <tr>
                            <td>Head</td>
                            <td>Head AR</td>
                        </tr>
                        @using RooyaDev.Models
                        @if(Session["Heads"]!=null)
                        {
                            foreach (var item in Session["Heads"] as List<Head>)
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.Name_AR
                                    </td>
                                </tr>
                                }
                        }
                    </table>
                </div>

            <form action="~/Services/Create" method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Name</span>
                    <input type="text" name="Name" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4" id="basic-addon3">Name AR</span>
                    <input type="text" name="Name_AR" required class="form-control col-md-8" id="basic-url" aria-describedby="basic-addon3">
                </div> <br />

                <div class="input-group textarea">
                    <span class="input-group col-md-4" id="basic-addon3"> Description</span>
                    <textarea class="form-control col-md-8" required name="Description" id="basic-url" aria-describedby="basic-addon3"> </textarea>
                </div> <br />
                <div class="input-group textarea">
                    <span class="input-group col-md-4" id="basic-addon3"> Description AR</span>
                    <textarea class="form-control col-md-8" required name="Description_AR" id="basic-url" aria-describedby="basic-addon3"> </textarea>
                </div> <br />
                <div class="input-group">
                    <span class="input-group col-md-4 myfile" id="basic-addon3">Upload Photo</span>
                    <input type="file" class="col-md-8" required name="Photo" id="basic-url" aria-describedby="basic-addon3" multiple>
                </div> <br />
                <button type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>
</div>

Views/Services/_DeleteHeads.cshtml
@model RooyaDev.Models.Service
<div id="DIV1">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Head</td>
            <td>Head AR</td>
            <td>Delete</td>
        </tr>
        @foreach (var item in Model.Heads)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Name_AR</td>
                <td>
                    @using (Ajax.BeginForm("DeleteHead", new { id = item.ID }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "DIV", InsertionMode = InsertionMode.Replace }))
                    {
                        <button type="submit"><i class="fa fa-times"></i></button>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Services/_Heads.cshtml
<div id="DIV">
    <table class="table table-info table-hover table-bordered">
        <tr>
            <td>Head</td>
            <td>Head AR</td>
        </tr>
        @using RooyaDev.Models
        @foreach (var item in Session["Heads"] as List<Head>)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Name_AR
                </td>
            </tr>
        }
    </table>
</div>